### PR TITLE
Rename Signin to DevSignin to make clear that the user selection is not real sign-in

### PR DESCRIPTION
**Pull request by daniv-msft**

### CODE REVIEW

**Comment by ynambiar** [comment]
Should we change some of the UI to reflect the change from sign-in to Dev sign-in? #Resolved

**Comment by daniv-msft** [comment]
> Actually, I couldn't find any place in the UI where we are displaying something such as "Sign-in", except the URL which is changed automagically in this PR by renaming the signin.js file. Do you have any specific UI in mind that I might have missed?
> 
> ---
> In reply to: [474509057](https://github.com/ContosoBikeRental/BikeSharingSampleApp/pull/22#issuecomment-474509057) [](ancestors = 474509057)

Maybe where it says "Select current user" it can say "Select a test user"? Open to other suggestions/opinions on this @johnsta @DrEsteban  #Resolved

**Review by ynambiar — APPROVED** [review]

**Comment by daniv-msft** [comment]
That sounds good to me! It makes clearer that these are test users, which is better. I'm sending an update with this.

---
In reply to: [474511879](https://github.com/ContosoBikeRental/BikeSharingSampleApp/pull/22#issuecomment-474511879) [](ancestors = 474511879,474509057)

**Comment by daniv-msft** [comment]
Hmm, it looks like CodeFlow for GitHub didn't like much my rebase. Anyway, checking-in.

---
In reply to: [474511879](https://github.com/ContosoBikeRental/BikeSharingSampleApp/pull/22#issuecomment-474511879) [](ancestors = 474511879)

**Pull request merged**
