### PR TITLE
Clean unused node packages

### PR DESCRIPTION
**Pull request by daniv-msft**
Also removed the packages-lock.json of BikeSharingWeb, as this was likely an artifact from a previous local install checked-in by mistake.

### CODE REVIEW

**Review by ynambiar — APPROVED** [review]
LGTM

**Comment by DrEsteban** [comment]
> {

Should we have a .gitignore to prevent this being checked in again? #Resolved

---
Refers to: BikeSharingWeb/package-lock.json:1 in cc789ef. [](commit_id = cc789ef0fb6806b2f28bafc2d9b200722ecd9058, deletion_comment = True)

**Review by DrEsteban — APPROVED** [review]
:shipit:

**Comment by daniv-msft** [comment]
> {

Sure! I added the rule in the main .gitignore.

---
In reply to: [482269938](https://github.com/ContosoBikeRental/BikeSharingSampleApp/pull/32#issuecomment-482269938) [](ancestors = 482269938)

---
Refers to: BikeSharingWeb/package-lock.json:1 in cc789ef. [](commit_id = cc789ef0fb6806b2f28bafc2d9b200722ecd9058, deletion_comment = True)

**Pull request merged**
